from setuptools import setup, find_packages

setup(
    name="otorecon",
    version="1.1",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "requests",
        "tqdm",
        "argparse",
        "colorama",
        "tldextract==2.2.3",
        "beautifulsoup4",
        "dnspython",
        "click",
        "py-altdns",
        "dnsgen",
        "sublist3r",
        "subbrute",
        "yagooglesearch==1.10.0",
        "python-whois",
        "fake-useragent",
        "urllib3",
        "uro",
        "google",
        "aiodns==3.2.0",
        "aiofiles==24.1.0",
        "aiohttp==3.11.11",
        "aiomultiprocess==0.9.1",
        "aiosqlite==0.20.0",
        "beautifulsoup4==4.12.3",
        "censys==2.2.16",
        "certifi==2024.12.14",
        "dnspython==2.7.0",
        "fastapi==0.115.7",
        "lxml==5.3.0",
        "netaddr==1.3.0",
        "ujson==5.10.0",
        "playwright==1.49.1",
        "PyYAML==6.0.2",
        "python-dateutil==2.9.0.post0",
        "requests==2.32.3",
        "retrying==1.3.4",
        "shodan==1.31.0",
        "slowapi==0.1.9",
        "uvicorn==0.34.0",
        "uvloop==0.21.0",
    ],
    author='Mr0Wido',
    author_email='furkn.dniz@protonmail.com',
    url='https://github.com/Mr0Wido/otorecon',
    description="OtoRecon - Automated Reconnaissance Toolkit",
    license="MIT",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: POSIX :: Linux",
    ],
    
)

